import type { Merchant } from "./merchants";
export const sampleMerchants: Merchant[] = [
  {
    name: "Wireless Bluetooth Headphones",
    category: "Electronics",
    price_cad: 49.99,
    description: "Over-ear wireless headphones with noise-canceling features",
    brand: "SoundMax",
    stock: 120,
    rating: 4.5,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Great sound quality",
        content: "Great sound quality and comfortable fit!",
      },
      {
        rating: 3,
        title: "Battery life could be better",
        content: "Battery life could be better.",
      },
      {
        rating: 4,
        title: "Excellent noise-canceling",
        content: "Excellent noise-canceling feature.",
      },
    ],
    image_url: "https://example.com/images/headphones.jpg",
    date_created: "2022-01-15",
  },
  {
    name: "Smart LED TV 50 inch",
    category: "Electronics",
    price_cad: 399.99,
    description: "50-inch 4K UHD Smart LED TV with streaming apps",
    brand: "ViewTech",
    stock: 60,
    rating: 4.7,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Amazing picture quality",
        content: "Amazing picture quality!",
      },
      {
        rating: 4,
        title: "User-friendly interface",
        content: "User-friendly interface.",
      },
      {
        rating: 3,
        title: "Speakers could be louder",
        content: "Speakers could be louder.",
      },
    ],
    image_url: "https://example.com/images/tv.jpg",
    date_created: "2022-01-10",
  },
  {
    name: "Running Shoes",
    category: "Apparel",
    price_cad: 59.99,
    description: "Lightweight running shoes with breathable mesh",
    brand: "FitRun",
    stock: 200,
    rating: 4.3,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Very comfortable",
        content: "Very comfortable for long runs.",
      },
      {
        rating: 4,
        title: "Stylish design",
        content: "Stylish design and good fit.",
      },
      {
        rating: 2,
        title: "Sole wore out quickly",
        content: "The sole wore out quickly.",
      },
    ],
    image_url: "https://example.com/images/shoes.jpg",
    date_created: "2022-01-05",
  },
  {
    name: "Stainless Steel Water Bottle",
    category: "Home & Kitchen",
    price_cad: 19.99,
    description: "Insulated stainless steel water bottle",
    brand: "HydroMax",
    stock: 500,
    rating: 4.8,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Keeps water cold",
        content: "Keeps water cold for hours.",
      },
      {
        rating: 4,
        title: "Leak-proof and durable",
        content: "Leak-proof and durable.",
      },
      {
        rating: 3,
        title: "A bit heavy",
        content: "A bit heavy to carry around.",
      },
    ],
    image_url: "https://example.com/images/water_bottle.jpg",
    date_created: "2022-01-01",
  },
  {
    name: "Wooden Coffee Table",
    category: "Furniture",
    price_cad: 129.99,
    description: "Modern wooden coffee table with storage shelf",
    brand: "HomeStyle",
    stock: 30,
    rating: 4.6,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Beautiful design",
        content: "Beautiful design and sturdy.",
      },
      {
        rating: 4,
        title: "Easy to assemble",
        content: "Easy to assemble.",
      },
      {
        rating: 3,
        title: "Surface scratches easily",
        content: "The surface scratches easily.",
      },
    ],
    image_url: "https://example.com/images/coffee_table.jpg",
    date_created: "2021-12-25",
  },
  {
    name: "Cotton Bath Towels (Set of 6)",
    category: "Home & Kitchen",
    price_cad: 39.99,
    description: "Soft and absorbent cotton bath towels",
    brand: "SoftTouch",
    stock: 150,
    rating: 4.4,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Very soft",
        content: "Very soft and comfortable.",
      },
      {
        rating: 4,
        title: "Dries quickly",
        content: "Dries quickly and stays fresh.",
      },
      {
        rating: 3,
        title: "Colors fade",
        content: "Some colors fade after washing.",
      },
    ],
    image_url: "https://example.com/images/bath_towels.jpg",
    date_created: "2021-12-20",
  },
  {
    name: "Smartphone 128GB",
    category: "Electronics",
    price_cad: 699.99,
    description: "Latest model smartphone with 128GB storage",
    brand: "TechBrand",
    stock: 75,
    rating: 4.9,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Fast performance",
        content: "Fast performance and great camera.",
      },
      {
        rating: 5,
        title: "Excellent battery life",
        content: "Excellent battery life.",
      },
      {
        rating: 4,
        title: "Expensive but worth it",
        content: "A bit expensive but worth it.",
      },
    ],
    image_url: "https://example.com/images/smartphone.jpg",
    date_created: "2021-12-15",
  },
  {
    name: "Laptop Backpack",
    category: "Accessories",
    price_cad: 45.99,
    description: "Durable laptop backpack with multiple compartments",
    brand: "TravelGear",
    stock: 90,
    rating: 4.2,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Lots of space",
        content: "Lots of space and well-padded.",
      },
      {
        rating: 4,
        title: "Comfortable to wear",
        content: "Comfortable to wear.",
      },
      {
        rating: 3,
        title: "Zippers could be better",
        content: "Zippers could be more robust.",
      },
    ],
    image_url: "https://example.com/images/backpack.jpg",
    date_created: "2021-12-10",
  },
  {
    name: "Electric Kettle",
    category: "Home & Kitchen",
    price_cad: 29.99,
    description: "1.7L electric kettle with auto shut-off feature",
    brand: "KitchenPro",
    stock: 80,
    rating: 4.5,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Boils water quickly",
        content: "Boils water quickly.",
      },
      {
        rating: 4,
        title: "Easy to clean",
        content: "Easy to clean and maintain.",
      },
      {
        rating: 3,
        title: "Lid is flimsy",
        content: "The lid is a bit flimsy.",
      },
    ],
    image_url: "https://example.com/images/kettle.jpg",
    date_created: "2021-12-05",
  },
  {
    name: "Yoga Mat",
    category: "Fitness",
    price_cad: 24.99,
    description: "Non-slip yoga mat with carrying strap",
    brand: "FlexFit",
    stock: 300,
    rating: 4.3,
    n_reviews: 3,
    reviews: [
      {
        rating: 5,
        title: "Good grip",
        content: "Good grip and cushioning.",
      },
      {
        rating: 4,
        title: "Lightweight",
        content: "Lightweight and portable.",
      },
      {
        rating: 3,
        title: "Gets dirty quickly",
        content: "Gets dirty quickly.",
      },
    ],
    image_url: "https://example.com/images/yoga_mat.jpg",
    date_created: "2021-12-01",
  },
];
